<?php

/**
 * BaseSite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $host
 * @property string $code
 * @property Doctrine_Collection $Clicks
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method string              getHost()   Returns the current record's "host" value
 * @method string              getCode()   Returns the current record's "code" value
 * @method Doctrine_Collection getClicks() Returns the current record's "Clicks" collection
 * @method Site                setName()   Sets the current record's "name" value
 * @method Site                setHost()   Sets the current record's "host" value
 * @method Site                setCode()   Sets the current record's "code" value
 * @method Site                setClicks() Sets the current record's "Clicks" collection
 * 
 * @package    heatmap
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('host', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Click as Clicks', array(
             'local' => 'id',
             'foreign' => 'site_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}