<?php

/**
 * BaseUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $site_id
 * @property string $url
 * 
 * @method integer getSiteId()  Returns the current record's "site_id" value
 * @method string  getUrl()     Returns the current record's "url" value
 * @method Url     setSiteId()  Sets the current record's "site_id" value
 * @method Url     setUrl()     Sets the current record's "url" value
 * 
 * @package    heatmap
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUrl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('url');
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}