<?php

/**
 * ClickTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClickTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClickTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Click');
    }
}