<?php

/**
 * UrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UrlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UrlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Url');
    }
}